export const employeeModelInputsCreate = (positions = [], departments = []) => [
    {
      key: "nombres",
      label: "Nombres",
      type: "text",
      required: true,
      maxLength: 100,
    },
    {
      key: "apellidos",
      label: "Apellidos",
      type: "text",
      required: true,
      maxLength: 100,
    },
    {
      key: "genero",
      label: "Género",
      type: "select",
      required: false,
      options: [
        { label: "Masculino", value: "Masculino" },
        { label: "Femenino", value: "Femenino" },
        { label: "Otro", value: "Otro" },
      ],
    },
    {
      key: "fechaNacimiento",
      label: "Fecha de Nacimiento",
      type: "date",
      required: false,
    },
    {
      key: "tipoDocumento",
      label: "Tipo de Documento",
      type: "text",
      required: false,
    },
    {
      key: "numeroDocumento",
      label: "Número de Documento",
      type: "text",
      required: false,
    },
    {
      key: "nacionalidad",
      label: "Nacionalidad",
      type: "text",
      required: false,
    },
    {
      key: "correo",
      label: "Correo Electrónico",
      type: "email",
      required: false,
    },
    {
      key: "telefono1",
      label: "Teléfono 1",
      type: "text",
      required: false,
    },
    {
      key: "telefono2",
      label: "Teléfono 2",
      type: "text",
      required: false,
    },
    {
      key: "direccion",
      label: "Dirección",
      type: "text",
      required: false,
    },
    {
      key: "departamentoResidencia",
      label: "Departamento de Residencia",
      type: "text",
      required: false,
    },
    {
      key: "municipioResidencia",
      label: "Municipio de Residencia",
      type: "text",
      required: false,
    },
    {
      key: "fechaIngreso",
      label: "Fecha de Ingreso",
      type: "date",
      required: false,
    },
    {
      key: "fechaEgreso",
      label: "Fecha de Egreso",
      type: "date",
      required: false,
    },
    {
      key: "tipoContrato",
      label: "Tipo de Contrato",
      type: "select",
      required: false,
      options: [
        { label: "Indefinido", value: "Indefinido" },
        { label: "Temporal", value: "Temporal" },
        { label: "Consultoría", value: "Consultoría" },
        { label: "Freelance", value: "Freelance" },
      ],
    },
    {
      key: "tipoEmpleado",
      label: "Tipo de Empleado",
      type: "text",
      required: false,
    },
    {
      key: "jornada",
      label: "Jornada",
      type: "text",
      required: false,
    },
    {
      key: "salario",
      label: "Salario",
      type: "number",
      required: false,
    },
    {
      key: "estadoEmpleado",
      label: "Estado del Empleado",
      type: "select",
      required: true,
      options: [
        { label: "Activo", value: "Activo" },
        { label: "Inactivo", value: "Inactivo" },
      ],
    },
    {
      key: "tipoSangre",
      label: "Tipo de Sangre",
      type: "text",
      required: false,
    },
    {
      key: "contactoEmergenciaNombre",
      label: "Nombre de Contacto de Emergencia",
      type: "text",
      required: false,
    },
    {
      key: "contactoEmergenciaParentesco",
      label: "Parentesco de Contacto de Emergencia",
      type: "text",
      required: false,
    },
    {
      key: "contactoEmergenciaTelefono",
      label: "Teléfono de Contacto de Emergencia",
      type: "text",
      required: false,
    },
    {
      key: "contactoEmergenciaDireccion",
      label: "Dirección de Contacto de Emergencia",
      type: "text",
      required: false,
    },
    {
      key: "observaciones",
      label: "Observaciones",
      type: "text",
      required: false,
    },
    {
      key: "notasInternas",
      label: "Notas Internas",
      type: "text",
      required: false,
    },
    {
      key: "idDepartamento",
      label: "Departamento",
      type: "select",
      required: true,
      options: departments.map((dep) => ({
        label: dep.nombreDepartamento,
        value: dep.idDepartamento,
      })),
    },
    {
      key: "puesto",
      label: "Puesto",
      type: "select",
      required: true,
      options: positions.map((p) => ({
        label: p.nombrePuesto + " - " + p.nombreDepartamento,
        value: p.idPuesto,
      })),
    },
  ];
  