import Sidebar from "@/components/Sidebar/Sidebar"; // Importa el Sidebar
import Topbar from "@/components/Sidebar/Topbar"; // Importa el Topbar
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";

// Configuración de las fuentes
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata del proyecto
export const metadata = {
  title: "SoftByte Commerce",
  description: "Generated by CacaoByte S.A",
  icons: {
    icon: "/Logo_CacaoByte_S.A.png", // Cambia la URL externa por la ruta local
    apple: "/Logo_CacaoByte_S.A.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/Logo_CacaoByte_S.A.png" // Cambia la URL externa por la ruta local
          type="image/png"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen">
          {/* Sidebar */}
          <Sidebar />

          {/* Contenedor principal */}
          <div className="flex flex-col flex-1">
            {/* Topbar */}
            <Topbar />

            {/* Contenido dinámico */}
            <main className="flex-1 bg-gray-50 p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
