import "../styles/globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ClientWrapper from "../components/shared/ClientWrapper";
import AppWrapper from "../components/AppWrapper"; // Importa el AppWrapper

export const metadata = {
  title: "SoftByte Commerce",
  description: "Generated by CacaoByte S.A",
  icons: {
    icon: "/Logo_CacaoByte_S.A.png",
    apple: "/Logo_CacaoByte_S.A.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Logo_CacaoByte_S.A.png" type="image/png" />
      </head>
      <body className="min-h-screen antialiased bg-gray-50 dark:bg-gray-800">
        <AppWrapper>
          <ClientWrapper>{children}</ClientWrapper>
          <ToastContainer
            position="top-center"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            style={{
              top: "50%",
              left: "50%",
              transform: "translate(-50%, -50%)",
              width: "90%",
              maxWidth: "400px",
            }}
          />
        </AppWrapper>
      </body>
    </html>
  );
}
