import React from "react";
import Sidebar from "@/components/sidebar/Sidebar"; // Sidebar mejorado
import Topbar from "@/components/sidebar/Topbar"; // Topbar mejorado
import { Geist, Azeret_Mono as Geist_Mono } from "next/font/google";
import "../styles/globals.css";

// Configuración de las fuentes
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata del proyecto
export const metadata = {
  title: "SoftByte Commerce",
  description: "Generated by CacaoByte S.A",
  icons: {
    icon: "/Logo_CacaoByte_S.A.png",
    apple: "/Logo_CacaoByte_S.A.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/Logo_CacaoByte_S.A.png" type="image/png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased bg-gray-50`}
      >
        <div className="flex h-screen overflow-hidden">
          {/* Sidebar */}
          <Sidebar />

          {/* Contenido principal */}
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Topbar */}
            <Topbar />

            {/* Contenido dinámico */}
            <main className="flex-1 overflow-y-auto bg-gray-100 p-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
