export const positionGenericModal = (departaments = []) => [
    {
      key: "idDepartamento",
      label: "Departamento",
      type: "select",
      required: true,
      options: departaments.map((dep) => ({
        value: dep.idDepartamento,
        label: dep.nombreDepartamento,
      })),
    },
    {
      key: "nombrePuesto",
      label: "Nombre del Puesto",
      type: "text",
      required: true,
      maxLength: 100,
      placeholder: "Ej. Asistente Administrativo",
    },
    {
      key: "descripcion",
      label: "Descripción",
      type: "text",
      required: false,
      maxLength: 255,
    },
    {
      key: "nivelJerarquico",
      label: "Nivel Jerárquico",
      type: "select",
      required: false,
      options: [
        { label: "Operativo", value: "Operativo" },
        { label: "Técnico", value: "Técnico" },
        { label: "Supervisión", value: "Supervisión" },
        { label: "Coordinación", value: "Coordinación" },
        { label: "Jefatura", value: "Jefatura" },
        { label: "Gerencia", value: "Gerencia" },
        { label: "Dirección", value: "Dirección" },
      ],
    },
    {
      key: "tipoPuesto",
      label: "Tipo de Puesto",
      type: "select",
      required: false,
      options: [
        { label: "Tiempo Completo", value: "Tiempo Completo" },
        { label: "Medio Tiempo", value: "Medio Tiempo" },
        { label: "Temporal", value: "Temporal" },
        { label: "Freelance", value: "Freelance" },
        { label: "Consultor", value: "Consultor" },
        { label: "Pasantía", value: "Pasantía" },
      ],
    },
    {
      key: "sueldoBase",
      label: "Sueldo Base",
      type: "number",
      required: false,
    },
    {
      key: "modalidadTrabajo",
      label: "Modalidad de Trabajo",
      type: "select",
      required: false,
      options: [
        { label: "Presencial", value: "Presencial" },
        { label: "Remoto", value: "Remoto" },
        { label: "Híbrido", value: "Híbrido" },
        { label: "Rotativo", value: "Rotativo" },
      ],
    },
    {
      key: "horarioTrabajo",
      label: "Horario de Trabajo",
      type: "select",
      required: false,
      options: [
        { label: "Lunes a Viernes de 7am a 4pm", value: "Lunes a Viernes de 7am a 4pm" },
        { label: "Lunes a Viernes de 8am a 5pm", value: "Lunes a Viernes de 8am a 5pm" },
        { label: "Lunes a Viernes de 9am a 6pm", value: "Lunes a Viernes de 9am a 6pm" },
        { label: "Lunes a Sábado de 7am a 12pm", value: "Lunes a Sábado de 7am a 12pm" },
        { label: "Lunes a Sábado de 12pm a 9pm", value: "Lunes a Sábado de 12pm a 9pm" },
        { label: "Lunes a Viernes de 6am a 5pm", value: "Lunes a Viernes de 6am a 5pm" },
        { label: "Turno Nocturno (10pm a 6am)", value: "Turno Nocturno (10pm a 6am)" },
        { label: "Horario Rotativo", value: "Horario Rotativo" },
      ],
    },
    {
      key: "requiereSupervision",
      label: "¿Requiere Supervisión?",
      type: "boolean",
      required: false,
    },
    {
      key: "esPuestoBase",
      label: "¿Es Puesto Base?",
      type: "boolean",
      required: false,
    },
    {
      key: "cantidadVacantes",
      label: "Cantidad de Vacantes",
      type: "number",
      required: false,
    },
    {
        key: "requisitosMinimos",
        label: "Requisitos Mínimos",
        type: "select",
        required: false,
        options: [
          { label: "Sin requisitos", value: "Sin requisitos" },
          { label: "Primaria completa", value: "Primaria completa" },
          { label: "Ciclo Básico / Educación Secundaria", value: "Ciclo Básico" },
          { label: "Diversificado / Educación Media (Bachillerato)", value: "Bachillerato" },
          { label: "Técnico medio o técnico universitario", value: "Técnico" },
          { label: "Licenciatura (Graduado)", value: "Licenciatura" },
          { label: "Licenciatura (En curso)", value: "Licenciatura (En curso)" },
          { label: "Maestría (Graduado)", value: "Maestría" },
          { label: "Maestría (En curso)", value: "Maestría (En curso)" },
          { label: "Doctorado (PhD)", value: "Doctorado" },
          { label: "Certificación profesional o especializada", value: "Certificación" },
          { label: "2+ años de experiencia", value: "2+ años de experiencia" },
          { label: "5+ años de experiencia", value: "5+ años de experiencia" },
          { label: "10+ años de experiencia", value: "10+ años de experiencia" },
        ],
    },
    {
      key: "capacitacionRequerida",
      label: "¿Requiere Capacitación?",
      type: "boolean",
      required: false,
    },
    {
      key: "riesgoLaboral",
      label: "Riesgo Laboral",
      type: "select",
      required: false,
      options: [
        { label: "Bajo", value: "Bajo" },
        { label: "Medio", value: "Medio" },
        { label: "Alto", value: "Alto" },
        { label: "Crítico", value: "Crítico" },
      ],
    },
    {
      key: "herramientasUtilizadas",
      label: "Herramientas Utilizadas",
      type: "text",
      required: false,
      placeholder: "Ej. Computadora, maquinaria, software específico",
    },
    {
      key: "uniformeRequerido",
      label: "¿Uniforme Requerido?",
      type: "boolean",
      required: false,
    },
    {
      key: "estado",
      label: "Estado",
      type: "boolean",
      required: true,
    },
    {
      key: "observaciones",
      label: "Observaciones",
      type: "text",
      maxLength: 250,
      placeholder: "Observaciones adicionales o notas importantes",
      required: false,
    },
  ];
  